//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.06 at 10:26:17 PM EST 
//


package model.person;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the model.person package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PersonRequest_QNAME = new QName("http://www.example.org/Person", "PersonRequest");
    private final static QName _PersonResponse_QNAME = new QName("http://www.example.org/Person", "PersonResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model.person
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PersonRequestType }
     * 
     */
    public PersonRequestType createPersonRequestType() {
        return new PersonRequestType();
    }

    /**
     * Create an instance of {@link PersonResponseType }
     * 
     */
    public PersonResponseType createPersonResponseType() {
        return new PersonResponseType();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link PersonId }
     * 
     */
    public PersonId createPersonId() {
        return new PersonId();
    }

    /**
     * Create an instance of {@link CountryCode }
     * 
     */
    public CountryCode createCountryCode() {
        return new CountryCode();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Person", name = "PersonRequest")
    public JAXBElement<PersonRequestType> createPersonRequest(PersonRequestType value) {
        return new JAXBElement<PersonRequestType>(_PersonRequest_QNAME, PersonRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Person", name = "PersonResponse")
    public JAXBElement<PersonResponseType> createPersonResponse(PersonResponseType value) {
        return new JAXBElement<PersonResponseType>(_PersonResponse_QNAME, PersonResponseType.class, null, value);
    }

}
